version: '3'
services:
  ba-project-jupyter:
    image: ba_project:latest
    build:
      context: ../
      dockerfile: ./binder/Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 8888:8888
    privileged: true
    # set group id of the host machine, so we can edit contents of the mounted volumes in the jupyterlab
    user: "${DOCKER_UID}:${DOCKER_GID}"
    #user: root
    working_dir: /home/jovyan
    command: jupyter lab --allow-root --NotebookApp.token='' --no-browser
    entrypoint: /home/jovyan/work/binder/entrypoint.sh
    volumes:
      - ../:/home/jovyan/work:rw
      - ../workspace:/workspace:rw
      # - /tmp/.X11-unix:/tmp/.X11-unix:rw
    # environment:
    #   - DISPLAY
    #   - QT_X11_NO_MITSHM=1
    
    
    
