version: '3'
services:
  ba-project-jupyter:
    image: ba_project:latest
    build:
      context: ../
      dockerfile: ./binder/Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 8888:8888
    privileged: true
    # set group id of the host machine, so we can edit contents of the mounted volumes in the jupyterlab
    user: "${DOCKER_UID}:${DOCKER_GID}"
    #user: root
    working_dir: /home/jovyan
    entrypoint: /home/jovyan/work/binder/entrypoint.sh
    command: >
      jupyter lab
      --allow-root
      --NotebookApp.token=''
      --no-browser
     #--workspace=/workspace/BA_workspace.jupyterlab-workspace
    
    volumes:
      - ../:/home/jovyan/work:rw
      - ../workspace:/workspace:rw
 
    
    
